"""
Schema Pack Registry — domain-specific schema bundles.

A pack is a named YAML manifest that lists node types and spaces
for a specific domain (e.g. biomedical, legal, saas).

Installing a pack creates YAML type schemas in schemas/types/ so they
are picked up by the loader and validated by the grammar validator.

Pack lifecycle:
  list_packs()           — show available packs
  get_pack(name)         — load pack manifest
  install_pack(name)     — generate type schemas from pack manifest
  uninstall_pack(name)   — remove generated type schemas (with safety check)
"""

from __future__ import annotations

import logging
from functools import lru_cache
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_PACKS_DIR = Path(__file__).parent / "packs"
_TYPES_DIR = Path(__file__).parent / "types"

# Minimal YAML template for a generated type schema
_TYPE_TEMPLATE = """\
# Auto-generated by schema pack '{pack_name}' v{pack_version}
# Remove this file or run pack uninstall to revert.
node_type: {node_type}
pack: {pack_name}
required: []
optional:
  - name
  - description
  - status
"""


def list_packs() -> list[dict[str, Any]]:
    """Return metadata for all available schema packs."""
    packs = []
    for path in sorted(_PACKS_DIR.glob("*.yaml")):
        try:
            import yaml  # type: ignore[import]
            with open(path, encoding="utf-8") as f:
                data = yaml.safe_load(f)
            if data and "name" in data:
                packs.append({
                    "name": data["name"],
                    "version": data.get("version", "unknown"),
                    "description": (data.get("description") or "").strip(),
                    "types": data.get("types", []),
                    "spaces": data.get("spaces", []),
                    "installed": _is_pack_installed(data["name"], data.get("types", [])),
                })
        except Exception as exc:
            logger.warning("Failed to load pack %s: %s", path.name, exc)
    return packs


def get_pack(name: str) -> dict[str, Any] | None:
    """Load a specific pack manifest by name."""
    path = _PACKS_DIR / f"{name}.yaml"
    if not path.exists():
        return None
    try:
        import yaml
        with open(path, encoding="utf-8") as f:
            return yaml.safe_load(f)
    except Exception as exc:
        logger.error("Failed to load pack '%s': %s", name, exc)
        return None


def install_pack(name: str) -> dict[str, Any]:
    """
    Install a schema pack by generating type YAML files.

    Each type in the pack gets a stub schema written to schemas/types/.
    Existing schemas are NOT overwritten (safety: user customisations preserved).

    Returns a result dict with created/skipped counts.
    """
    pack = get_pack(name)
    if not pack:
        return {"error": f"Pack '{name}' not found. Available: {[p['name'] for p in list_packs()]}"}

    _TYPES_DIR.mkdir(parents=True, exist_ok=True)

    created = []
    skipped = []

    for node_type in pack.get("types", []):
        path = _TYPES_DIR / f"{node_type}.yaml"
        if path.exists():
            skipped.append(node_type)
            continue
        content = _TYPE_TEMPLATE.format(
            pack_name=pack["name"],
            pack_version=pack.get("version", "1.0.0"),
            node_type=node_type,
        )
        path.write_text(content, encoding="utf-8")
        created.append(node_type)
        logger.info("Pack '%s': created schema for %s", name, node_type)

    # Invalidate loader cache
    try:
        from opencrab.schemas.loader import reload_schema
        for t in created:
            reload_schema(t)
    except Exception:
        pass

    return {
        "pack": name,
        "version": pack.get("version"),
        "created": created,
        "skipped": skipped,
        "total_types": len(pack.get("types", [])),
    }


def uninstall_pack(name: str, force: bool = False) -> dict[str, Any]:
    """
    Remove type schemas generated by a pack.

    Only removes schemas that have `pack: <name>` in their YAML header
    (i.e. were auto-generated). User-customised schemas are kept unless
    force=True.
    """
    pack = get_pack(name)
    if not pack:
        return {"error": f"Pack '{name}' not found."}

    removed = []
    kept = []

    for node_type in pack.get("types", []):
        path = _TYPES_DIR / f"{node_type}.yaml"
        if not path.exists():
            continue
        try:
            content = path.read_text(encoding="utf-8")
            is_generated = f"pack: {name}" in content
            if is_generated or force:
                path.unlink()
                removed.append(node_type)
            else:
                kept.append(node_type)
        except Exception as exc:
            logger.warning("Failed to remove schema %s: %s", node_type, exc)
            kept.append(node_type)

    return {
        "pack": name,
        "removed": removed,
        "kept_user_customised": kept,
    }


def _is_pack_installed(name: str, types: list[str]) -> bool:
    """Return True if at least one type from the pack has a schema file."""
    return any((_TYPES_DIR / f"{t}.yaml").exists() for t in types)
